pipeline {
    agent any

    stages {
        stage('Checkout Code') {
            steps {
                git branch: 'main', url: 'https://github.com/ishvit23/ASSIGNMENT_2.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                bat 'docker build -t flask-docker-app .'
            }
        }

        stage('Run Docker Container') {
            steps {
                script {
                    bat 'docker stop flask-app || echo "Not running"'
                    bat 'docker rm flask-app || echo "Not found"'
                    bat 'docker run -d --name flask-app -p 5000:5000 flask-docker-app'
                }
            }
        }

        stage('Verify App Running') {
            steps {
                bat '''
                    curl -s http://localhost:5000 || (echo "App not responding!" && exit /b 1)
                '''
            }
        }
    }

    post {
        always {
            // Clean up container (optional)
            bat 'docker stop flask-app || echo "Not running"'
            bat 'docker rm flask-app || echo "Not found"'
        }
    }
}
