pipeline {
    agent any

    environment {
        IMAGE_NAME = 'flask-docker-app'
        CONTAINER_NAME = 'flask-app'
        PORT = '5000'
    }

    stages {
        stage('Checkout Code') {
            steps {
                git branch: 'main', url: 'https://github.com/ishvit23/ASSIGNMENT_2.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                bat "docker build -t %IMAGE_NAME% ."
            }
        }

        stage('Stop & Remove Old Container') {
            steps {
                script {
                    bat '''
                        docker ps -q -f name=%CONTAINER_NAME% && docker stop %CONTAINER_NAME% || echo "No container running"
                        docker ps -aq -f name=%CONTAINER_NAME% && docker rm %CONTAINER_NAME% || echo "No container to remove"
                    '''
                }
            }
        }

        stage('Run Docker Container') {
            steps {
                bat "docker run -d -p %PORT%:5000 --name %CONTAINER_NAME% %IMAGE_NAME%"
            }
        }

        stage('Verify App Running') {
            steps {
                bat "curl http://localhost:%PORT%"
            }
        }
    }

    post {
        always {
            echo 'Pipeline finished!'
        }
        failure {
            echo 'Something went wrong. Check the logs.'
        }
    }
}
