pipeline {
    agent any

    stages {
        stage('Clone') {
            steps {
                git 'https://github.com/ishvit23/ASSIGNMENT_2.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    docker.build("flask-docker-app")
                }
            }
        }

        stage('Run Container') {
            steps {
                script {
                    sh 'docker stop flask-app || true'
                    sh 'docker rm flask-app || true'
                    sh 'docker run -d --name flask-app -p 5000:5000 flask-docker-app'
                }
            }
        }
    }
}
